kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: jenkins-agent-ansible
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/ch007m/jenkins-agent-ansible.git"
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: "jenkins-agent-ansible:latest"
  triggers:
    - type: GitHub
      github:
        secret: "123"